import { motion, useReducedMotion } from "framer-motion";
import { scaleIn } from "@/lib/variants";

interface DishCardProps {
  id?: string;
  title: string;
  ingredients: string[];
  cost: number;
  prepTime?: string;
  calories?: number;
  description?: string;
  backdropImage?: string;
}

export default function DishCard({
  id,
  title,
  ingredients,
  cost,
  prepTime = "18 mins",
  calories = 540,
  description = "A custom recipe generated by our AI agent. Combining freshly sourced ingredients with modern culinary techniques, verified against active kitchen inventory.",
  backdropImage
}: DishCardProps) {
  const prefersReducedMotion = useReducedMotion();

  const getIngredientColor = (idx: number) => {
    const schemas = [
      "bg-brand/10 border-brand/20 text-brand",
      "bg-brand-orange/10 border-brand-orange/20 text-brand-orange",
      "bg-emerald-600/10 border-emerald-600/20 text-emerald-800",
      "bg-teal-600/10 border-teal-600/20 text-teal-800"
    ];
    return schemas[idx % schemas.length];
  };

  return (
    <motion.div
      data-dish-id={id}
      data-dish-name={title}
      className="group w-full mt-6 rounded-[2rem] border border-[#e9e5da] bg-[#fffdf9]/90 p-3 shadow-[0_16px_40px_rgba(29,58,43,0.08)] transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_22px_55px_rgba(29,58,43,0.14)]"
      variants={scaleIn}
      initial="hidden"
      whileInView="visible"
      viewport={{ once: true, amount: 0.2 }}
      whileHover={prefersReducedMotion ? undefined : { scale: 1.04, boxShadow: "0 24px 60px rgba(29, 58, 43, 0.16)" }}
      transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
    >
      <h2 className="mb-3.5 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.24em] text-[#1d3a2b]/65">
        <span className="h-2.5 w-2.5 rounded-full bg-[#e59b27]"></span>
        Synthesized recipe details
      </h2>

      <div className="overflow-hidden rounded-[1.5rem] border border-[#e9e5da] bg-white shadow-[0_10px_28px_rgba(29,58,43,0.06)] transition-all duration-300">
        {/* Dynamic Plating Backdrop */}
        <div className="relative flex h-52 w-full items-center justify-center overflow-hidden border-b border-[#e9e5da] bg-[#f5efe4]">
          {backdropImage ? (
            <>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={backdropImage}
                alt={title}
                className="absolute inset-0 h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.05]"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent"></div>
            </>
          ) : (
            <div className="absolute inset-0 bg-gradient-to-br from-[#1d3a2b]/10 to-[#e59b27]/10"></div>
          )}

          {/* Steaming Food Vector Logo */}
          <div className="relative z-10 flex flex-col items-center gap-2">
            <div className="flex h-14 w-14 items-center justify-center rounded-full border border-white/70 bg-white shadow-[0_10px_24px_rgba(29,58,43,0.12)]">
              <svg className="h-7 w-7 text-[#1d3a2b]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364-6.364l-.707.707M6.343 17.657l-.707.707m0-12.728l.707.707m11.314 11.314l.707.707M12 8a4 4 0 100 8 4 4 0 000-8z" />
              </svg>
            </div>
            <span className="rounded-full border border-white/70 bg-white px-2.5 py-0.5 text-[9px] font-semibold uppercase tracking-[0.22em] text-[#1d3a2b]">
              Verified Composition
            </span>
          </div>
        </div>

        {/* Card Details */}
        <div className="p-6">
          <div className="flex flex-col md:flex-row justify-between items-start gap-4">
            <div className="flex-1">
              <h3 className="text-xl font-bold tracking-tight text-[#1d3a2b]">{title}</h3>
              <p className="mt-2 text-sm leading-relaxed italic text-[#1d3a2b]/68">{description}</p>
            </div>
            <div className="text-left md:text-right flex-shrink-0">
              <span className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#1d3a2b]/42">Estimated Cost</span>
              <p className="text-3xl font-bold text-[#1d3a2b]">₹{cost}</p>
            </div>
          </div>

          {/* Quick Metrics Bar */}
          <div className="my-5 grid grid-cols-3 gap-2 rounded-2xl border border-[#e9e5da] bg-[#faf7f0] px-3 py-4 text-center">
            <div>
              <span className="block text-[10px] font-semibold uppercase tracking-[0.18em] text-[#1d3a2b]/42">Prep Time</span>
              <span className="text-sm font-bold text-[#1d3a2b]">⏱️ {prepTime}</span>
            </div>
            <div>
              <span className="block text-[10px] font-semibold uppercase tracking-[0.18em] text-[#1d3a2b]/42">Energy</span>
              <span className="text-sm font-bold text-[#1d3a2b]">🔥 {calories} kcal</span>
            </div>
            <div>
              <span className="block text-[10px] font-semibold uppercase tracking-[0.18em] text-[#1d3a2b]/42">Kitchen Queue</span>
              <span className="text-sm font-bold text-emerald-700">⚡ Available Now</span>
            </div>
          </div>

          {/* Ingredient Chips */}
          <div>
            <span className="mb-2.5 block text-xs font-semibold uppercase tracking-[0.18em] text-[#1d3a2b]/68">
              Verified Ingredients:
            </span>
            <div className="flex flex-wrap gap-2">
              {ingredients.map((ingredient, idx) => (
                <span
                  key={ingredient}
                  className={`rounded-full border px-3 py-1.5 text-xs font-semibold transition-all duration-200 hover:-translate-y-0.5 ${getIngredientColor(idx)}`}
                >
                  🥗 {ingredient}
                </span>
              ))}
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
