interface DishCardProps {
  title: string;
  ingredients: string[];
  cost: number;
  prepTime?: string;
  calories?: number;
  description?: string;
  backdropImage?: string;
}

export default function DishCard({
  title,
  ingredients,
  cost,
  prepTime = "18 mins",
  calories = 540,
  description = "A custom recipe generated by our AI agent. Combining freshly sourced ingredients with modern culinary techniques, verified against active kitchen inventory.",
  backdropImage
}: DishCardProps) {

  const getIngredientColor = (idx: number) => {
    const schemas = [
      "bg-brand/10 border-brand/20 text-brand",
      "bg-brand-orange/10 border-brand-orange/20 text-brand-orange",
      "bg-emerald-600/10 border-emerald-600/20 text-emerald-800",
      "bg-teal-600/10 border-teal-600/20 text-teal-800"
    ];
    return schemas[idx % schemas.length];
  };

  return (
    <div className="w-full mt-6 animate-fade-in">
      <h2 className="text-xs font-bold text-brand/80 uppercase tracking-wider mb-3.5 flex items-center gap-2">
        <span className="w-2.5 h-2.5 rounded-full bg-brand-orange"></span>
        IV. Synthesized Recipe Details
      </h2>

      <div className="bg-white rounded-2xl overflow-hidden shadow-md transition-all duration-300 border border-zinc-200">
        {/* Dynamic Plating Backdrop */}
        <div className="relative h-52 w-full bg-zinc-100 flex items-center justify-center overflow-hidden border-b border-zinc-200">
          {backdropImage ? (
            <>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={backdropImage}
                alt={title}
                className="absolute inset-0 w-full h-full object-cover transition-all duration-500 hover:scale-102"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent"></div>
            </>
          ) : (
            <div className="absolute inset-0 bg-gradient-to-br from-brand/10 to-brand-orange/10"></div>
          )}

          {/* Steaming Food Vector Logo */}
          <div className="relative z-10 flex flex-col items-center gap-2">
            <div className="w-14 h-14 rounded-full bg-white flex items-center justify-center shadow-md border border-brand-orange">
              <svg className="w-7 h-7 text-brand" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364-6.364l-.707.707M6.343 17.657l-.707.707m0-12.728l.707.707m11.314 11.314l.707.707M12 8a4 4 0 100 8 4 4 0 000-8z" />
              </svg>
            </div>
            <span className="text-[9px] uppercase font-bold tracking-widest text-brand bg-white px-2.5 py-0.5 rounded-full border border-zinc-200">
              Verified Composition
            </span>
          </div>
        </div>

        {/* Card Details */}
        <div className="p-6">
          <div className="flex flex-col md:flex-row justify-between items-start gap-4">
            <div className="flex-1">
              <h3 className="text-xl font-bold text-brand tracking-tight">{title}</h3>
              <p className="text-sm text-zinc-600 mt-2 leading-relaxed italic">{description}</p>
            </div>
            <div className="text-left md:text-right flex-shrink-0">
              <span className="text-xs text-zinc-400 font-bold uppercase tracking-wider">Estimated Cost</span>
              <p className="text-3xl font-bold text-brand">₹{cost}</p>
            </div>
          </div>

          {/* Quick Metrics Bar */}
          <div className="grid grid-cols-3 gap-2 my-5 py-3 border-y border-zinc-150 text-center bg-zinc-50 rounded-xl">
            <div>
              <span className="block text-[10px] uppercase tracking-wider text-zinc-400 font-bold">Prep Time</span>
              <span className="text-sm font-bold text-zinc-800">⏱️ {prepTime}</span>
            </div>
            <div>
              <span className="block text-[10px] uppercase tracking-wider text-zinc-400 font-bold">Energy</span>
              <span className="text-sm font-bold text-zinc-800">🔥 {calories} kcal</span>
            </div>
            <div>
              <span className="block text-[10px] uppercase tracking-wider text-zinc-400 font-bold">Kitchen Queue</span>
              <span className="text-sm font-bold text-emerald-700">⚡ Available Now</span>
            </div>
          </div>

          {/* Ingredient Chips */}
          <div>
            <span className="block text-xs font-bold text-brand/80 uppercase tracking-wider mb-2.5">
              Verified Ingredients:
            </span>
            <div className="flex flex-wrap gap-2">
              {ingredients.map((ingredient, idx) => (
                <span
                  key={ingredient}
                  className={`text-xs font-bold px-3 py-1.5 rounded-xl border transition-all ${getIngredientColor(idx)}`}
                >
                  🥗 {ingredient}
                </span>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
