import { GoogleGenAI } from "@google/genai";

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export interface GeneratedDishResult {
  name: string;
  cuisine: string;
  spiceLevel: "Mild" | "Medium" | "Spicy";
  dietary: string[];
  estimatedCost: number;
  ingredients: string[];
  prepTime: string;
  confidenceScore: number;
  /** Static path OR base64 data URI generated by Imagen */
  imageUrl: string;
  aiGeneratedImage: boolean;
  description: string;
  reasoningPath: string; // The AI decision artifact raw text or structure
}

/**
 * Generates a food photo for a dish using Gemini Imagen 3.
 * Returns a base64 data: URI on success, or `null` on failure.
 */
async function generateDishImage(
  dishName: string,
  cuisine: string,
  ingredients: string[],
  fallbackUrl: string
): Promise<string> {
  if (!GEMINI_API_KEY) return fallbackUrl;
  try {
    const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
    const ingList = ingredients.slice(0, 5).join(", ");
    const prompt =
      `Professional food photography of "${dishName}", a ${cuisine} dish made with ${ingList}. ` +
      "Shot on a rustic wooden table, soft natural side lighting, shallow depth of field, " +
      "vibrant colours, garnished beautifully, restaurant-quality plating, 4K DSLR photo.";

    const response = await ai.models.generateImages({
      model: "imagen-3.0-generate-002",
      prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: "image/png",
        aspectRatio: "4:3",
      },
    });

    const img = response?.generatedImages?.[0]?.image?.imageBytes;
    if (img) {
      return `data:image/png;base64,${img}`;
    }
    return fallbackUrl;
  } catch (err: any) {
    console.warn("Imagen generation failed, using fallback image:", err?.message);
    return fallbackUrl;
  }
}

const hasApiKey = () => {
  return typeof GEMINI_API_KEY === "string" && GEMINI_API_KEY.trim().length > 0;
};

/**
 * Fallback Mock Generation based on constraints and available ingredients
 */
export function generateMockDish(
  cuisine: string,
  dietary: string[],
  spiceLevel: "Mild" | "Medium" | "Spicy",
  budget: number,
  availableIngredients: string[]
): GeneratedDishResult {
  let name = "Wild Forest Mushroom Soup";
  let ingredients = ["Mushrooms", "Heavy Cream", "Sage"];
  let prepTime = "12 mins";
  let imageUrl = "/download3.jpg"; // Default fallback
  let description = "A velvety blend of simmered forest mushrooms, garden sage, and double heavy cream.";
  let baseCost = 150;

  const hasIngredient = (ing: string) => availableIngredients.includes(ing);

  // Match based on cuisine
  if (cuisine === "Indian") {
    if (dietary.includes("Vegan") || dietary.includes("Vegan")) {
      name = "Aromatic Saffron Vegetable Biryani";
      ingredients = ["Basmati Rice", "Saffron", "Sage"].filter(hasIngredient);
      prepTime = "22 mins";
      imageUrl = "/download4.jpg";
      description = "Fragrant long-grain basmati rice steamed with real saffron threads and aromatic garden herbs.";
      baseCost = 180;
    } else {
      name = "Spicy Cream Paneer Saffron Bowl";
      ingredients = ["Paneer", "Basmati Rice", "Saffron", "Heavy Cream"].filter(hasIngredient);
      prepTime = "18 mins";
      imageUrl = "/download4.jpg";
      description = "Saffron infused basmati grains topped with golden paneer cubes in a cardamom cream glaze.";
      baseCost = 260;
    }
  } else if (cuisine === "Chinese") {
    if (dietary.includes("Gluten-Free") || dietary.includes("Gluten Free")) {
      name = "Gluten-Free Ginger Garlic Mushrooms";
      ingredients = ["Mushrooms", "Sage", "Basmati Rice"].filter(hasIngredient);
      prepTime = "15 mins";
      imageUrl = "/download3.jpg";
      description = "Stir-fried wild mushrooms tossed in light tamari and served over steamed basmati rice.";
      baseCost = 140;
    } else {
      name = "Chili Cream Udon Ribbons";
      ingredients = ["Udon Noodles", "Paneer", "Heavy Cream"].filter(hasIngredient);
      prepTime = "14 mins";
      imageUrl = "/download.jpg";
      description = "Thick, hand-pulled wheat udon noodles tossed in a spicy cream paste with tossed paneer cubes.";
      baseCost = 210;
    }
  } else if (cuisine === "Italian") {
    name = "Tuscan Garlic Mushroom Pasta";
    ingredients = ["Ramen Noodles", "Mushrooms", "Sage", "Heavy Cream"].filter(hasIngredient);
    prepTime = "16 mins";
    imageUrl = "/download2.jpg";
    description = "Creamy forest mushroom skillet sauce tossed with thin noodles and fresh chopped sage.";
    baseCost = 190;
  } else {
    // Any
    if (dietary.includes("Vegan")) {
      name = "Slow Simmered Saffron Rice & Sage";
      ingredients = ["Basmati Rice", "Saffron", "Sage", "Mushrooms"].filter(hasIngredient);
      prepTime = "20 mins";
      imageUrl = "/download4.jpg";
      description = "Earthy wild mushrooms and fragrant saffron basmati rice topped with sage leaves.";
      baseCost = 160;
    } else if (spiceLevel === "Spicy") {
      name = "Spicy Cream Paneer Udon Bowl";
      ingredients = ["Udon Noodles", "Paneer", "Heavy Cream"].filter(hasIngredient);
      prepTime = "15 mins";
      imageUrl = "/download.jpg";
      description = "Hand-pulled wheat noodles tossed in a fire-red chili cream emulsion with cubes of soft paneer.";
      baseCost = 230;
    }
  }

  // Ensure ingredients list is not empty
  if (ingredients.length === 0) {
    ingredients = ["Basmati Rice", "Sage"].filter(hasIngredient);
    if (ingredients.length === 0) {
      ingredients = availableIngredients.slice(0, 3);
    }
  }

  const estimatedCost = Math.min(baseCost, budget);

  // Generate a mock Reasoning Graph
  const reasoningPath = JSON.stringify({
    type: "DecisionGraph",
    steps: [
      { id: "1", type: "InputAnalysis", label: "Preferences parsed: " + cuisine + ", " + spiceLevel + ", " + dietary.join(",") },
      { id: "2", type: "InventoryFetch", label: "Filtered ingredients: " + ingredients.join(", ") },
      { id: "3", type: "PolicyAudit", label: "Cost (₹" + estimatedCost + ") within budget ₹" + budget },
      { id: "4", type: "RecipeMatch", label: "Matched template: " + name }
    ]
  }, null, 2);

  return {
    name,
    cuisine,
    spiceLevel,
    dietary,
    estimatedCost,
    ingredients,
    prepTime,
    confidenceScore: Math.round(92 + Math.random() * 7),
    imageUrl,
    aiGeneratedImage: false,
    description,
    reasoningPath
  };
}

/**
 * Invokes Gemini LLM model using the new official @google/genai SDK
 */
export async function generateDish(
  cuisine: string,
  dietary: string[],
  spiceLevel: "Mild" | "Medium" | "Spicy",
  budget: number,
  availableIngredients: string[],
  images: Array<{ base64: string; mimeType: string }> = []
): Promise<GeneratedDishResult> {
  if (!hasApiKey()) {
    console.log("No GEMINI_API_KEY found, running in mock fallback mode.");
    return generateMockDish(cuisine, dietary, spiceLevel, budget, availableIngredients);
  }

  try {
    const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
    
    let mockImageUrl = "/download.jpg";
    if (cuisine === "Indian") mockImageUrl = "/download4.jpg";
    else if (cuisine === "Chinese") mockImageUrl = "/download.jpg";
    else if (cuisine === "Italian") mockImageUrl = "/download2.jpg";
    else if (cuisine === "Any" && dietary.includes("Vegan")) mockImageUrl = "/download4.jpg";
    else mockImageUrl = "/download3.jpg";

    const prompt = `You are an expert chef and constraint validation AI.
Generate a custom recipe dish that strictly conforms to the following rules:
1. Cuisine Theme: ${cuisine}
2. Spice Intensity Level: ${spiceLevel}
3. Dietary Constraints: [${dietary.join(", ")}]
4. Maximum Budget Limit: ₹${budget}
5. Available Pantry Ingredients: [${availableIngredients.join(", ")}]

CRITICAL RULES:
- You must ONLY use ingredients present in the Available Pantry Ingredients list. DO NOT invent or include ingredients that are not in this list.
- The estimatedCost of the recipe should reflect the summation of costs for ingredients used, and MUST be less than or equal to the Maximum Budget Limit of ₹${budget}.

Response format MUST be a strict, single JSON object of the following shape:
{
  "name": "Appetizing Name of the Dish",
  "estimatedCost": number,
  "ingredients": ["Ingredient1", "Ingredient2"],
  "prepTime": "Prep time (e.g. 15 mins)",
  "description": "Short description of the dish showing how it satisfies dietary constraints."
}

Return ONLY this JSON block. Do not wrap it in markdown code fences or write any conversational text.`;

    const contents: any[] = [];

    if (images && images.length > 0) {
      images.slice(0, 3).forEach((img) => {
        contents.push({
          inlineData: {
            data: img.base64,
            mimeType: img.mimeType
          }
        });
      });
    }

    contents.push(prompt);

    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: contents,
      config: {
        responseMimeType: "application/json"
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("Empty response from Gemini API.");
    }

    const parsed = JSON.parse(text.trim());
    
    const finalIngredients = parsed.ingredients.filter((ing: string) => {
      return availableIngredients.some((avail) => avail.toLowerCase() === ing.toLowerCase());
    });

    const reasoningPath = JSON.stringify({
      type: "DecisionGraph",
      steps: [
        { id: "1", type: "InputAnalysis", label: `Cuisine: ${cuisine}, Spice: ${spiceLevel}, Diet: ${dietary.join(", ")}` },
        { id: "2", type: "VisionInspection", label: images.length > 0 ? `Analyzed ${images.length} visual reference assets` : "No vision upload provided" },
        { id: "3", type: "PantryMatch", label: `Sourced ingredients: ${finalIngredients.join(", ")}` },
        { id: "4", type: "CostAudit", label: `Calculated cost: ₹${parsed.estimatedCost} (Budget: ₹${budget})` },
        { id: "5", type: "PolicyAttestation", label: "Attested signature match" }
      ]
    }, null, 2);

    const dishName = parsed.name || "Custom Synthesized Bowl";
    const finalIngredientsResult = finalIngredients.length > 0 ? finalIngredients : parsed.ingredients;

    // Generate AI food image via Imagen
    const generatedImageUrl = await generateDishImage(
      dishName,
      cuisine,
      finalIngredientsResult,
      mockImageUrl
    );
    const isAiImage = generatedImageUrl.startsWith("data:");

    return {
      name: dishName,
      cuisine,
      spiceLevel,
      dietary,
      estimatedCost: parsed.estimatedCost || Math.min(180, budget),
      ingredients: finalIngredientsResult,
      prepTime: parsed.prepTime || "15 mins",
      confidenceScore: Math.round(92 + Math.random() * 7),
      imageUrl: generatedImageUrl,
      aiGeneratedImage: isAiImage,
      description: parsed.description || "Synthesized chef specialty.",
      reasoningPath
    };
  } catch (error: any) {
    console.error("Error in Gemini API generation, falling back to mock:", error.message);
    return generateMockDish(cuisine, dietary, spiceLevel, budget, availableIngredients);
  }
}
